/**
 * 前端硬编码菜单配置
 *
 * 对齐原 Java nms-web router/index.js：菜单为前端硬编码，
 * 通过路由 meta.permissionsOr/permissionsAnd/isAdmin 控制可见性。
 *
 * 菜单项与 router/modules/static.ts 中的路由对应。
 *
 * 菜单 name 通过 i18n key 动态转换：
 *   - 若 i18n key 存在，使用 t(key)
 *   - 否则回退到 fallbackName
 *
 * 本菜单树对齐老版 nms-web 的完整结构（Base Station / CPE / ... / System）。
 */

import type { MenuItem } from '@/types';

export interface MenuConfig {
  id: number;
  parentId: number;
  /** 菜单 i18n key（如 menu.dashboard） */
  i18nKey: string;
  /** 菜单 i18n 缺失时的兜底名称（兼容旧版本） */
  fallbackName: string;
  code: string;
  type: MenuItem['type'];
  path: string;
  component?: string;
  icon?: string;
  permission?: string;
  permissionsOr?: string[];
  permissionsAnd?: string[];
  isAdmin?: boolean;
  sort: number;
  visible: MenuItem['visible'];
  keepAlive?: boolean;
  isExternal?: boolean;
  children?: MenuConfig[];
}

export const staticMenuConfigs: MenuConfig[] = [
  // 1. Dashboard
  {
    id: 100,
    parentId: 0,
    i18nKey: 'menu.dashboard',
    fallbackName: '仪表盘',
    code: 'dashboard',
    type: 'menu',
    path: '/dashboard',
    component: 'dashboard/index',
    icon: 'Odometer',
    sort: 1,
    visible: 'visible',
    keepAlive: true,
  },

  // 2. Base Station 基站
  {
    id: 200,
    parentId: 0,
    i18nKey: 'menu.baseStation',
    fallbackName: '基站',
    code: 'base-station',
    type: 'directory',
    path: '/base-station',
    component: 'Layout',
    icon: 'Monitor',
    sort: 2,
    visible: 'visible',
    permissionsOr: [
      'GNB.Monitor.ListGNB',
      'ENB.Monitor.ListENB',
      'MML.BatchExecuteMML',
      'MML.ImportMMLAndParameter',
      'MML.Script.ListBatchProcessFileLog',
      'MML.Script.ListBatchProcessFile',
      'MML.Script.ListExecuteResultFileLog',
      'Device.Upgrade.ListUpgradeTask',
      'Device.Upgrade.ListUpgradeResult',
      'Device.Upgrade.ListRollbackTask',
      'Device.Upgrade.ListUpgradeFile',
      'Device.Reboot.ListRebootTask',
      'Device.Reset.ListResetTask',
      'ShutDown.ListShutdownTask',
      'Maintenance.BackupAndRestore.ListBaseStationBackupLatestFileInfo',
      'Device.Log.ListGNBDeviceLogCollectionResult',
      'GNB.Logs.ListGNBEventLog',
      'GNB.Logs.ListBaseStationValueChangeLog',
      'CBSDCertFile.ListDeviceCBSDCertFile',
      'BaseStation.License.ListLicense',
      'DeviceMNormalFile.List',
      'CaTask.List',
      'CaFile.List',
      'SSH.Access.ListTimer',
    ],
    children: [
      {
        id: 201,
        parentId: 200,
        i18nKey: 'menu.gnbMonitor',
        fallbackName: 'gNB 监控',
        code: 'gnb-monitor',
        type: 'menu',
        path: '/device/list',
        component: 'device/list',
        icon: 'Monitor',
        sort: 1,
        visible: 'visible',
        keepAlive: true,
        permissionsAnd: ['GNB.Monitor.ListGNB'],
      },
      {
        id: 202,
        parentId: 200,
        i18nKey: 'menu.enbMonitor',
        fallbackName: 'eNB 监控',
        code: 'enb-monitor',
        type: 'menu',
        path: '/base-station/enb-monitor',
        component: 'placeholder/index',
        icon: 'Monitor',
        sort: 2,
        visible: 'visible',
        permissionsAnd: ['ENB.Monitor.ListENB'],
      },
      // Maintenance 维护
      {
        id: 210,
        parentId: 200,
        i18nKey: 'menu.bsMaintenance',
        fallbackName: '维护',
        code: 'bs-maintenance',
        type: 'directory',
        path: '/base-station/maintenance',
        icon: 'Tools',
        sort: 3,
        visible: 'visible',
        permissionsOr: [
          'MML.BatchExecuteMML',
          'MML.ImportMMLAndParameter',
          'MML.Script.ListBatchProcessFileLog',
          'MML.Script.ListBatchProcessFile',
          'MML.Script.ListExecuteResultFileLog',
          'Device.Upgrade.ListUpgradeTask',
          'Device.Upgrade.ListUpgradeResult',
          'Device.Upgrade.ListRollbackTask',
          'Device.Upgrade.ListUpgradeFile',
          'Device.Reboot.ListRebootTask',
          'Device.Reset.ListResetTask',
          'ShutDown.ListShutdownTask',
          'Maintenance.BackupAndRestore.ListBaseStationBackupLatestFileInfo',
          'Device.Log.ListGNBDeviceLogCollectionResult',
          'GNB.Logs.ListGNBEventLog',
          'GNB.Logs.ListBaseStationValueChangeLog',
          'BaseStation.License.ListLicense',
          'DeviceMNormalFile.List',
          'CaTask.List',
          'CaFile.List',
          'SSH.Access.ListTimer',
        ],
        children: [
          {
            id: 211,
            parentId: 210,
            i18nKey: 'menu.mml',
            fallbackName: 'MML',
            code: 'bs-mml',
            type: 'menu',
            path: '/system/mml',
            component: 'system/mml',
            icon: 'List',
            sort: 1,
            visible: 'visible',
            permissionsOr: [
              'MML.BatchExecuteMML',
              'MML.ImportMMLAndParameter',
              'MML.Script.ListBatchProcessFileLog',
              'MML.Script.ListBatchProcessFile',
              'MML.Script.ListExecuteResultFileLog',
            ],
          },
          {
            id: 212,
            parentId: 210,
            i18nKey: 'menu.sshAccess',
            fallbackName: 'SSH 访问计时器',
            code: 'ssh-access',
            type: 'menu',
            path: '/base-station/ssh-access',
            component: 'placeholder/index',
            icon: 'Timer',
            sort: 2,
            visible: 'visible',
            permissionsOr: ['SSH.Access.ListTimer'],
          },
          {
            id: 213,
            parentId: 210,
            i18nKey: 'menu.bsUpgrade',
            fallbackName: '升级',
            code: 'bs-upgrade',
            type: 'menu',
            path: '/base-station/upgrade',
            component: 'placeholder/index',
            icon: 'UploadFilled',
            sort: 3,
            visible: 'visible',
            permissionsOr: [
              'Device.Upgrade.ListUpgradeTask',
              'Device.Upgrade.ListUpgradeResult',
              'Device.Upgrade.ListRollbackTask',
              'Device.Upgrade.ListUpgradeFile',
            ],
          },
          {
            id: 214,
            parentId: 210,
            i18nKey: 'menu.bsLicense',
            fallbackName: '证书',
            code: 'bs-license',
            type: 'menu',
            path: '/base-station/license',
            component: 'placeholder/index',
            icon: 'Key',
            sort: 4,
            visible: 'visible',
            permissionsAnd: ['BaseStation.License.ListLicense'],
          },
          {
            id: 215,
            parentId: 210,
            i18nKey: 'menu.ca',
            fallbackName: 'CA',
            code: 'bs-ca',
            type: 'menu',
            path: '/system/cacert',
            component: 'system/cacert',
            icon: 'Key',
            sort: 5,
            visible: 'visible',
            permissionsOr: ['CaTask.List', 'CaFile.List'],
          },
          {
            id: 216,
            parentId: 210,
            i18nKey: 'menu.normalFile',
            fallbackName: '常规文件',
            code: 'bs-normal-file',
            type: 'menu',
            path: '/system/normalfile',
            component: 'system/normalfile',
            icon: 'Folder',
            sort: 6,
            visible: 'visible',
            permissionsOr: ['DeviceMNormalFile.List'],
          },
          {
            id: 217,
            parentId: 210,
            i18nKey: 'menu.reboot',
            fallbackName: '重启',
            code: 'bs-reboot',
            type: 'menu',
            path: '/base-station/reboot',
            component: 'placeholder/index',
            icon: 'RefreshRight',
            sort: 7,
            visible: 'visible',
            permissionsOr: ['Device.Reboot.ListRebootTask'],
          },
          {
            id: 218,
            parentId: 210,
            i18nKey: 'menu.reset',
            fallbackName: '重置',
            code: 'bs-reset',
            type: 'menu',
            path: '/base-station/reset',
            component: 'placeholder/index',
            icon: 'RefreshLeft',
            sort: 8,
            visible: 'visible',
            permissionsOr: ['Device.Reset.ListResetTask'],
          },
          {
            id: 219,
            parentId: 210,
            i18nKey: 'menu.shutdownTask',
            fallbackName: '关机任务',
            code: 'bs-shutdown',
            type: 'menu',
            path: '/base-station/shutdown',
            component: 'placeholder/index',
            icon: 'SwitchButton',
            sort: 9,
            visible: 'visible',
            permissionsOr: ['ShutDown.ListShutdownTask'],
          },
          {
            id: 220,
            parentId: 210,
            i18nKey: 'menu.bsBackup',
            fallbackName: '备份/恢复',
            code: 'bs-backup',
            type: 'menu',
            path: '/system/bsbackup',
            component: 'system/bsbackup',
            icon: 'DataBackup',
            sort: 10,
            visible: 'visible',
            permissionsOr: ['Maintenance.BackupAndRestore.ListBaseStationBackupLatestFileInfo'],
          },
          {
            id: 221,
            parentId: 210,
            i18nKey: 'menu.neighborCell',
            fallbackName: '相邻小区',
            code: 'bs-neighbor',
            type: 'menu',
            path: '/base-station/neighbor-cell',
            component: 'placeholder/index',
            icon: 'Connection',
            sort: 11,
            visible: 'visible',
            permissionsOr: ['ModelTree.ExportNeighbourCellInfo'],
          },
          {
            id: 222,
            parentId: 210,
            i18nKey: 'menu.bsLog',
            fallbackName: '日志',
            code: 'bs-log',
            type: 'menu',
            path: '/monitor/device-log',
            component: 'monitor/device-log',
            icon: 'Files',
            sort: 12,
            visible: 'visible',
            permissionsOr: [
              'Device.Log.ListGNBDeviceLogCollectionResult',
              'GNB.Logs.ListGNBEventLog',
              'GNB.Logs.ListBaseStationValueChangeLog',
            ],
          },
        ],
      },
      {
        id: 230,
        parentId: 200,
        i18nKey: 'menu.cbsdCertFile',
        fallbackName: 'CBSD 证书文件',
        code: 'bs-cbsd-cert',
        type: 'menu',
        path: '/network/cbsd',
        component: 'network/cbsd',
        icon: 'Connection',
        sort: 4,
        visible: 'visible',
        permissionsAnd: ['CBSDCertFile.ListDeviceCBSDCertFile'],
      },
    ],
  },

  // 3. CPE
  {
    id: 300,
    parentId: 0,
    i18nKey: 'menu.cpe',
    fallbackName: 'CPE',
    code: 'cpe',
    type: 'directory',
    path: '/cpe',
    component: 'Layout',
    icon: 'Cellphone',
    sort: 3,
    visible: 'visible',
    permissionsOr: [
      'CPE.Monitor.ListCPE',
      'CPE.Upgrade.ListUpgradeTask',
      'CPE.Upgrade.ListUpgradeResult',
      'CPE.Upgrade.ListUpgradeFile',
      'CPE.Reboot.ListRebootTask',
      'Device.Log.ListCPEDeviceLogCollectionResult',
      'CPE.Log.ListCpeEventLog',
      'CPE.Log.ListCPEValueChangeLog',
      'CBSDCertFile.ListDeviceCBSDCertFile',
    ],
    children: [
      {
        id: 301,
        parentId: 300,
        i18nKey: 'menu.cpeMonitor',
        fallbackName: '监控',
        code: 'cpe-monitor',
        type: 'menu',
        path: '/cpe/monitor',
        component: 'placeholder/index',
        icon: 'Monitor',
        sort: 1,
        visible: 'visible',
        permissionsOr: ['CPE.Monitor.ListCPE'],
      },
      {
        id: 310,
        parentId: 300,
        i18nKey: 'menu.cpeMaintenance',
        fallbackName: '维护',
        code: 'cpe-maintenance',
        type: 'directory',
        path: '/cpe/maintenance',
        icon: 'Tools',
        sort: 2,
        visible: 'visible',
        permissionsOr: [
          'CPE.Upgrade.ListUpgradeTask',
          'CPE.Upgrade.ListUpgradeResult',
          'CPE.Upgrade.ListUpgradeFile',
          'CPE.Reboot.ListRebootTask',
          'Device.Log.ListCPEDeviceLogCollectionResult',
          'CPE.Log.ListCpeEventLog',
          'CPE.Log.ListCPEValueChangeLog',
        ],
        children: [
          {
            id: 311,
            parentId: 310,
            i18nKey: 'menu.cpeUpgrade',
            fallbackName: '升级',
            code: 'cpe-upgrade',
            type: 'menu',
            path: '/cpe/upgrade',
            component: 'placeholder/index',
            icon: 'UploadFilled',
            sort: 1,
            visible: 'visible',
            permissionsOr: [
              'CPE.Upgrade.ListUpgradeTask',
              'CPE.Upgrade.ListUpgradeResult',
              'CPE.Upgrade.ListUpgradeFile',
            ],
          },
          {
            id: 312,
            parentId: 310,
            i18nKey: 'menu.cpeReboot',
            fallbackName: '重启',
            code: 'cpe-reboot',
            type: 'menu',
            path: '/cpe/reboot',
            component: 'placeholder/index',
            icon: 'RefreshRight',
            sort: 2,
            visible: 'visible',
            permissionsOr: ['CPE.Reboot.ListRebootTask'],
          },
          {
            id: 313,
            parentId: 310,
            i18nKey: 'menu.cpeLog',
            fallbackName: '日志',
            code: 'cpe-log',
            type: 'menu',
            path: '/cpe/log',
            component: 'placeholder/index',
            icon: 'Files',
            sort: 3,
            visible: 'visible',
            permissionsOr: [
              'Device.Log.ListCPEDeviceLogCollectionResult',
              'CPE.Log.ListCpeEventLog',
              'CPE.Log.ListCPEValueChangeLog',
            ],
          },
        ],
      },
      {
        id: 320,
        parentId: 300,
        i18nKey: 'menu.cpeCbsdCert',
        fallbackName: 'CBSD 证书文件',
        code: 'cpe-cbsd-cert',
        type: 'menu',
        path: '/cpe/cbsd-cert',
        component: 'placeholder/index',
        icon: 'Connection',
        sort: 3,
        visible: 'visible',
        permissionsAnd: ['CBSDCertFile.ListDeviceCBSDCertFile'],
      },
    ],
  },

  // 4. Device Group 设备组
  {
    id: 400,
    parentId: 0,
    i18nKey: 'menu.deviceGroup',
    fallbackName: '设备组',
    code: 'device-group',
    type: 'menu',
    path: '/device/group',
    component: 'device/group',
    icon: 'Files',
    sort: 4,
    visible: 'visible',
    keepAlive: true,
    permissionsAnd: ['DeviceGroup.ListDeviceGroup'],
  },

  // 5. Cluster 群组
  {
    id: 500,
    parentId: 0,
    i18nKey: 'menu.cluster',
    fallbackName: '群组',
    code: 'cluster',
    type: 'menu',
    path: '/cluster',
    component: 'placeholder/index',
    icon: 'Collection',
    sort: 5,
    visible: 'visible',
    permissionsAnd: ['Cluster.ListCluster'],
  },

  // 6. Core Network 核心网
  {
    id: 600,
    parentId: 0,
    i18nKey: 'menu.coreNetwork',
    fallbackName: '核心网',
    code: 'core-network',
    type: 'menu',
    path: '/network/core-network',
    component: 'network/core-network',
    icon: 'OfficeBuilding',
    sort: 6,
    visible: 'visible',
    permissionsAnd: ['CoreNetwork.ListCoreNetwork'],
  },

  // 7. GIS
  {
    id: 700,
    parentId: 0,
    i18nKey: 'menu.gis',
    fallbackName: 'GIS',
    code: 'gis',
    type: 'menu',
    path: '/gis',
    component: 'placeholder/index',
    icon: 'MapLocation',
    sort: 7,
    visible: 'visible',
    permissionsAnd: ['Map.ListDeviceWithLocationInfoInDeviceGroup'],
  },

  // 8. Site 站点
  {
    id: 800,
    parentId: 0,
    i18nKey: 'menu.site',
    fallbackName: '站点',
    code: 'site',
    type: 'menu',
    path: '/network/site',
    component: 'network/site',
    icon: 'Place',
    sort: 8,
    visible: 'visible',
    permissionsAnd: ['Site.ListSites'],
  },

  // 9. ZTP
  {
    id: 900,
    parentId: 0,
    i18nKey: 'menu.ztp',
    fallbackName: 'ZTP',
    code: 'ztp',
    type: 'menu',
    path: '/system/ztp',
    component: 'system/ztp',
    icon: 'MagicStick',
    sort: 9,
    visible: 'visible',
    permissionsOr: ['ZTP.ListZTPResults', 'ZTP.ListTBG'],
  },

  // 10. Alarm 告警
  {
    id: 1000,
    parentId: 0,
    i18nKey: 'menu.alarm',
    fallbackName: '告警',
    code: 'alarm',
    type: 'menu',
    path: '/monitor/alarm',
    component: 'monitor/alarm',
    icon: 'Bell',
    sort: 10,
    visible: 'visible',
    permissionsOr: ['Alarm.ListAlarm', 'Alarm.ListAlarmLibraries'],
  },

  // 11. Performance 性能
  {
    id: 1100,
    parentId: 0,
    i18nKey: 'menu.performance',
    fallbackName: '性能',
    code: 'performance',
    type: 'menu',
    path: '/report/pm',
    component: 'report/pm',
    icon: 'DataAnalysis',
    sort: 11,
    visible: 'visible',
    permissionsOr: [
      'Performance.KPITemplate.ListKPITemplate',
      'Performance.KPIMeas.ListKPIMeas',
      'Performance.ListKPIAlarmTemplate',
      'Performance.KPISet.ListKPISet',
      'Performance.Replenish.List',
    ],
  },

  // 12. Advance 高级
  {
    id: 1200,
    parentId: 0,
    i18nKey: 'menu.advance',
    fallbackName: '高级',
    code: 'advance',
    type: 'directory',
    path: '/advance',
    component: 'Layout',
    icon: 'SetUp',
    sort: 12,
    visible: 'visible',
    permissionsOr: ['SAS.ListCBSD'],
    children: [
      {
        id: 1201,
        parentId: 1200,
        i18nKey: 'menu.sas',
        fallbackName: 'SAS',
        code: 'sas',
        type: 'menu',
        path: '/advance/sas',
        component: 'placeholder/index',
        icon: 'Connection',
        sort: 1,
        visible: 'visible',
        permissionsAnd: ['SAS.ListCBSD'],
      },
    ],
  },

  // 13. Batch Tasks 批量任务
  {
    id: 1300,
    parentId: 0,
    i18nKey: 'menu.batchTasks',
    fallbackName: '批量任务',
    code: 'batch-tasks',
    type: 'directory',
    path: '/batch',
    component: 'Layout',
    icon: 'Tickets',
    sort: 13,
    visible: 'visible',
    permissionsOr: [
      'ValueMonitor.ListMonitorTask',
      'Configuration.ListBatchConfiguration',
      'ParameterTemplate.List',
      'ParameterMonitor.List',
      'BatchTask.ParameterDeploy.List',
      'Configuration.ListBatchAddObjectTask',
    ],
    children: [
      {
        id: 1301,
        parentId: 1300,
        i18nKey: 'menu.batchMonitor',
        fallbackName: '监控',
        code: 'batch-monitor',
        type: 'menu',
        path: '/device/param-monitor',
        component: 'device/param-monitor',
        icon: 'TrendCharts',
        sort: 1,
        visible: 'visible',
        keepAlive: true,
        permissionsAnd: ['ValueMonitor.ListMonitorTask'],
      },
      {
        id: 1302,
        parentId: 1300,
        i18nKey: 'menu.batchConfig',
        fallbackName: '配置',
        code: 'batch-config',
        type: 'menu',
        path: '/device/parameter',
        component: 'device/parameter',
        icon: 'Setting',
        sort: 2,
        visible: 'visible',
        keepAlive: true,
        permissionsOr: [
          'Configuration.ListBatchConfiguration',
          'ParameterTemplate.List',
          'ParameterMonitor.List',
          'BatchTask.ParameterDeploy.List',
        ],
      },
      {
        id: 1303,
        parentId: 1300,
        i18nKey: 'menu.addObject',
        fallbackName: '添加实例',
        code: 'batch-object',
        type: 'menu',
        path: '/batch/object',
        component: 'placeholder/index',
        icon: 'Plus',
        sort: 3,
        visible: 'visible',
        permissionsAnd: ['Configuration.ListBatchAddObjectTask'],
      },
    ],
  },

  // 14. MR Manage MR 管理
  {
    id: 1400,
    parentId: 0,
    i18nKey: 'menu.mrManage',
    fallbackName: 'MR 管理',
    code: 'mr-manage',
    type: 'menu',
    path: '/report/mr',
    component: 'report/mr',
    icon: 'TrendCharts',
    sort: 14,
    visible: 'visible',
    permissionsOr: ['MR.ListMRUploadTask', 'MR.ListMRUploadLatestTime'],
  },

  // 15. Device Blocklist 设备黑名单
  {
    id: 1500,
    parentId: 0,
    i18nKey: 'menu.deviceBlocklist',
    fallbackName: '设备黑名单',
    code: 'device-blocklist',
    type: 'menu',
    path: '/system/blacklist',
    component: 'system/blacklist',
    icon: 'CircleClose',
    sort: 15,
    visible: 'visible',
    permissionsOr: ['DeviceBlackList.ListDeviceBlackList', 'DeviceBlackList.ListBlackListOperationLog'],
  },

  // 16. System 系统
  {
    id: 1600,
    parentId: 0,
    i18nKey: 'menu.system',
    fallbackName: '系统',
    code: 'system',
    type: 'directory',
    path: '/system',
    component: 'Layout',
    icon: 'Setting',
    sort: 16,
    visible: 'visible',
    isAdmin: true,
    permissionsOr: [
      'System.Settings.ListDeviceSettings',
      'System.Settings.ListACSSettings',
      'System.Settings.GetMailSetting',
      'System.Resource.GetCPUAndMemUsage',
      'System.Log.ListOperationLog',
      'System.Upgrade.ListUpgradeFile',
      'System.License.GetLicenseInfo',
      'System.Authority.SecurityRule.GetSecurityRule',
      'System.Authority.User.ListUser',
      'System.Authority.Role.GetRolePermissions',
      'System.Tenant.ListTenancy',
      'System.SSO.AddRadius',
      'System.SSO.AddEntraEndPoint',
      'System.NorthReport.ListNorthReport',
      'System.Maintenance.ListNTPConfig',
      'NMSBacupAndRevert.ListNMSBackupTask',
      'SSHLabel.ListSSHLabels',
      'Tcpdump.ListTcpdumpFiles',
      'Area.ListArea',
      'TR069.Parameter.ListTR069Parameter',
      'TR069.ParameterSet.GetParameterSet',
    ],
    children: [
      {
        id: 1601,
        parentId: 1600,
        i18nKey: 'menu.settings',
        fallbackName: '设置',
        code: 'sys-settings',
        type: 'menu',
        path: '/system/settings',
        component: 'system/settings',
        icon: 'Setting',
        sort: 1,
        visible: 'visible',
        permissionsOr: [
          'System.Settings.ListDeviceSettings',
          'System.Settings.ListACSSettings',
          'System.Settings.GetMailSetting',
        ],
      },
      // Maintenance 维护
      {
        id: 1610,
        parentId: 1600,
        i18nKey: 'menu.sysMaintenance',
        fallbackName: '维护',
        code: 'sys-maintenance',
        type: 'directory',
        path: '/system/maintenance',
        icon: 'Tools',
        sort: 2,
        visible: 'visible',
        permissionsOr: [
          'SSHLabel.ListSSHLabels',
          'Tcpdump.ListTcpdumpFiles',
          'System.Maintenance.PING',
          'System.Maintenance.ListNTPConfig',
        ],
        children: [
          {
            id: 1611,
            parentId: 1610,
            i18nKey: 'menu.ssh',
            fallbackName: 'SSH',
            code: 'sys-ssh',
            type: 'menu',
            path: '/system/ssh',
            component: 'system/ssh',
            icon: 'Terminal',
            sort: 1,
            visible: 'visible',
            permissionsAnd: ['SSHLabel.ListSSHLabels'],
          },
          {
            id: 1612,
            parentId: 1610,
            i18nKey: 'menu.ping',
            fallbackName: 'PING',
            code: 'sys-ping',
            type: 'menu',
            path: '/system/diagnostics',
            component: 'system/diagnostics',
            icon: 'Aim',
            sort: 2,
            visible: 'visible',
            permissionsAnd: ['System.Maintenance.PING'],
          },
          {
            id: 1613,
            parentId: 1610,
            i18nKey: 'menu.tcpdump',
            fallbackName: '网络数据采集分析',
            code: 'sys-tcpdump',
            type: 'menu',
            path: '/system/tcpdump',
            component: 'system/tcpdump',
            icon: 'Monitor',
            sort: 3,
            visible: 'visible',
            permissionsAnd: ['Tcpdump.ListTcpdumpFiles'],
          },
          {
            id: 1614,
            parentId: 1610,
            i18nKey: 'menu.ntp',
            fallbackName: 'NTP',
            code: 'sys-ntp',
            type: 'menu',
            path: '/system/ntp',
            component: 'system/ntp',
            icon: 'Timer',
            sort: 4,
            visible: 'visible',
            permissionsAnd: ['System.Maintenance.ListNTPConfig'],
          },
        ],
      },
      {
        id: 1620,
        parentId: 1600,
        i18nKey: 'menu.load',
        fallbackName: '负载',
        code: 'sys-load',
        type: 'menu',
        path: '/system/resources',
        component: 'system/resources',
        icon: 'Cpu',
        sort: 3,
        visible: 'visible',
        permissionsAnd: ['System.Resource.GetCPUAndMemUsage'],
      },
      {
        id: 1621,
        parentId: 1600,
        i18nKey: 'menu.northInterface',
        fallbackName: '北向',
        code: 'sys-north',
        type: 'menu',
        path: '/system/north-interface',
        component: 'placeholder/index',
        icon: 'Promotion',
        sort: 4,
        visible: 'visible',
        permissionsOr: ['System.NorthReport.ListNorthReport'],
      },
      {
        id: 1622,
        parentId: 1600,
        i18nKey: 'menu.sysLog',
        fallbackName: '日志',
        code: 'sys-log',
        type: 'menu',
        path: '/system/log',
        component: 'system/log/index',
        icon: 'Document',
        sort: 5,
        visible: 'visible',
        permissionsOr: [
          'System.Log.ListLoginLog',
          'System.Log.ListOperationLog',
          'System.Log.UpdateLogConfig',
        ],
      },
      {
        id: 1623,
        parentId: 1600,
        i18nKey: 'menu.dataModel',
        fallbackName: '数据模型',
        code: 'sys-data-model',
        type: 'menu',
        path: '/system/data-model',
        component: 'placeholder/index',
        icon: 'Files',
        sort: 6,
        visible: 'visible',
        permissionsOr: ['TR069.Parameter.ListTR069Parameter', 'TR069.ParameterSet.GetParameterSet'],
      },
      {
        id: 1624,
        parentId: 1600,
        i18nKey: 'menu.sysUpgrade',
        fallbackName: '升级',
        code: 'sys-upgrade',
        type: 'menu',
        path: '/system/upgrade',
        component: 'system/upgrade',
        icon: 'UploadFilled',
        sort: 7,
        visible: 'visible',
        permissionsAnd: ['System.Upgrade.ListUpgradeFile'],
      },
      {
        id: 1625,
        parentId: 1600,
        i18nKey: 'menu.sysBackup',
        fallbackName: '备份与恢复',
        code: 'sys-backup',
        type: 'menu',
        path: '/system/backup',
        component: 'system/backup',
        icon: 'DataBackup',
        sort: 8,
        visible: 'visible',
        permissionsAnd: ['NMSBacupAndRevert.ListNMSBackupTask'],
      },
      {
        id: 1626,
        parentId: 1600,
        i18nKey: 'menu.sysLicense',
        fallbackName: '许可证',
        code: 'sys-license',
        type: 'menu',
        path: '/system/license',
        component: 'system/license/index',
        icon: 'Key',
        sort: 9,
        visible: 'visible',
        permissionsAnd: ['System.License.GetLicenseInfo'],
      },
      {
        id: 1627,
        parentId: 1600,
        i18nKey: 'menu.authority',
        fallbackName: '权限',
        code: 'sys-authority',
        type: 'menu',
        path: '/system/authority',
        component: 'system/authority/index',
        icon: 'User',
        sort: 10,
        visible: 'visible',
        permissionsOr: [
          'System.Authority.User.ListUser',
          'System.Authority.Role.GetRolePermissions',
          'System.Tenant.ListTenancy',
          'System.Authority.SecurityRule.GetSecurityRule',
          'System.SSO.AddRadius',
          'System.SSO.AddEntraEndPoint',
        ],
      },
      {
        id: 1628,
        parentId: 1600,
        i18nKey: 'menu.area',
        fallbackName: '区域',
        code: 'sys-area',
        type: 'menu',
        path: '/system/area',
        component: 'placeholder/index',
        icon: 'MapLocation',
        sort: 11,
        visible: 'visible',
        permissionsAnd: ['Area.ListArea'],
      },
    ],
  },

  // profile（hidden 保留）
  {
    id: 9900,
    parentId: 0,
    i18nKey: 'menu.profile',
    fallbackName: '个人中心',
    code: 'profile',
    type: 'menu',
    path: '/profile',
    component: 'profile/index',
    icon: 'User',
    sort: 99,
    visible: 'hidden',
  },
];

/**
 * 将 MenuConfig 转换为 MenuItem（运行时根据 locale 解析 name）
 */
export function resolveMenuItems(configs: MenuConfig[], t: (key: string) => string): MenuItem[] {
  return configs.map((c) => ({
    id: c.id,
    parentId: c.parentId,
    name: safeT(t, c.i18nKey, c.fallbackName),
    code: c.code,
    type: c.type,
    path: c.path,
    component: c.component,
    icon: c.icon,
    permission: c.permission,
    permissionsOr: c.permissionsOr,
    permissionsAnd: c.permissionsAnd,
    isAdmin: c.isAdmin,
    sort: c.sort,
    visible: c.visible,
    keepAlive: c.keepAlive,
    isExternal: c.isExternal,
    children: c.children ? resolveMenuItems(c.children, t) : undefined,
  }));
}

function safeT(t: (key: string) => string, key: string, fallback: string): string {
  try {
    const v = t(key);
    if (v && v !== key) return v;
  } catch {
    // ignore
  }
  return fallback;
}
