/**
 * 前端硬编码菜单配置
 *
 * 对齐原 Java nms-web router/index.js：菜单为前端硬编码，
 * 通过路由 meta.permissionsOr/permissionsAnd/isAdmin 控制可见性。
 *
 * 菜单项与 router/modules/static.ts 中的路由对应。
 */

import type { MenuItem } from '@/types';

/**
 * 静态菜单树（用于侧边栏渲染）
 *
 * 说明：
 *  - permissionsOr：任一权限满足即显示
 *  - permissionsAnd：所有权限都满足才显示
 *  - isAdmin：仅管理员可见
 *  - 无权限配置的菜单所有人可见
 */
export const staticMenus: MenuItem[] = [
  {
    id: 1,
    parentId: 0,
    name: '仪表盘',
    code: 'dashboard',
    type: 'menu',
    path: '/dashboard',
    component: 'dashboard/index',
    icon: 'Odometer',
    sort: 1,
    visible: 'visible',
    keepAlive: true,
  },
  {
    id: 2,
    parentId: 0,
    name: '设备管理',
    code: 'device',
    type: 'directory',
    path: '/device',
    component: 'Layout',
    icon: 'Monitor',
    sort: 2,
    visible: 'visible',
    children: [
      {
        id: 21,
        parentId: 2,
        name: '设备列表',
        code: 'device-list',
        type: 'menu',
        path: '/device/list',
        component: 'device/list',
        icon: 'List',
        sort: 1,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 25,
        parentId: 2,
        name: '设备运维',
        code: 'device-ops',
        type: 'menu',
        path: '/device/ops',
        component: 'device/ops',
        icon: 'Operation',
        sort: 5,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 22,
        parentId: 2,
        name: '参数管理',
        code: 'parameter-management',
        type: 'menu',
        path: '/device/parameter',
        component: 'device/parameter',
        icon: 'Setting',
        sort: 2,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 23,
        parentId: 2,
        name: '参数监控',
        code: 'param-monitor',
        type: 'menu',
        path: '/device/param-monitor',
        component: 'device/param-monitor',
        icon: 'TrendCharts',
        sort: 3,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 24,
        parentId: 2,
        name: '参数对比',
        code: 'param-compare',
        type: 'menu',
        path: '/device/param-compare',
        component: 'device/param-compare',
        icon: 'DocumentCopy',
        sort: 4,
        visible: 'visible',
        keepAlive: true,
      },
    ],
  },
  {
    id: 3,
    parentId: 0,
    name: '监控告警',
    code: 'monitor',
    type: 'directory',
    path: '/monitor',
    component: 'Layout',
    icon: 'Bell',
    sort: 3,
    visible: 'visible',
    permissionsOr: ['Alarm.ListAlarm'],
    children: [
      {
        id: 31,
        parentId: 3,
        name: '告警列表',
        code: 'alarm-list',
        type: 'menu',
        path: '/monitor/alarm',
        component: 'monitor/alarm',
        icon: 'Warning',
        sort: 1,
        visible: 'visible',
        permissionsOr: ['Alarm.ListAlarm'],
      },
      {
        id: 32,
        parentId: 3,
        name: '事件日志',
        code: 'event-log',
        type: 'menu',
        path: '/monitor/event-log',
        component: 'monitor/event-log',
        icon: 'Document',
        sort: 2,
        visible: 'visible',
      },
      {
        id: 33,
        parentId: 3,
        name: '设备日志',
        code: 'device-log',
        type: 'menu',
        path: '/monitor/device-log',
        component: 'monitor/device-log',
        icon: 'Files',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 34,
        parentId: 3,
        name: '监控任务',
        code: 'monitor-task',
        type: 'menu',
        path: '/monitor/monitor-task',
        component: 'monitor/monitor-task',
        icon: 'DataLine',
        sort: 4,
        visible: 'visible',
      },
    ],
  },
  {
    id: 6,
    parentId: 0,
    name: '网络管理',
    code: 'network',
    type: 'directory',
    path: '/network',
    component: 'Layout',
    icon: 'MapLocation',
    sort: 5,
    visible: 'visible',
    children: [
      {
        id: 61,
        parentId: 6,
        name: '站点管理',
        code: 'site-manage',
        type: 'menu',
        path: '/network/site',
        component: 'network/site',
        icon: 'MapLocation',
        sort: 1,
        visible: 'visible',
      },
      {
        id: 62,
        parentId: 6,
        name: '拓扑管理',
        code: 'topology-manage',
        type: 'menu',
        path: '/network/topology',
        component: 'network/topology',
        icon: 'Share',
        sort: 2,
        visible: 'visible',
      },
      {
        id: 63,
        parentId: 6,
        name: 'CBSD 管理',
        code: 'cbsd-manage',
        type: 'menu',
        path: '/network/cbsd',
        component: 'network/cbsd',
        icon: 'Connection',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 64,
        parentId: 6,
        name: '核心网',
        code: 'core-network',
        type: 'menu',
        path: '/network/core-network',
        component: 'network/core-network',
        icon: 'Monitor',
        sort: 4,
        visible: 'visible',
      },
    ],
  },
  {
    id: 4,
    parentId: 0,
    name: '系统设置',
    code: 'system',
    type: 'directory',
    path: '/system',
    component: 'Layout',
    icon: 'Setting',
    sort: 4,
    visible: 'visible',
    isAdmin: true,
    children: [
      {
        id: 41,
        parentId: 4,
        name: '用户管理',
        code: 'user-manage',
        type: 'menu',
        path: '/system/user',
        component: 'system/user',
        icon: 'User',
        sort: 1,
        visible: 'visible',
        permissionsOr: ['System.Authority.User.ListUser'],
      },
      {
        id: 42,
        parentId: 4,
        name: '角色管理',
        code: 'role-manage',
        type: 'menu',
        path: '/system/role',
        component: 'system/role',
        icon: 'UserFilled',
        sort: 2,
        visible: 'visible',
        permissionsOr: ['System.Authority.Role.ListRole'],
      },
      {
        id: 43,
        parentId: 4,
        name: '升级管理',
        code: 'upgrade-manage',
        type: 'menu',
        path: '/system/upgrade',
        component: 'system/upgrade',
        icon: 'UploadFilled',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 44,
        parentId: 4,
        name: '系统配置',
        code: 'system-settings',
        type: 'menu',
        path: '/system/settings',
        component: 'system/settings',
        icon: 'Setting',
        sort: 4,
        visible: 'visible',
      },
      {
        id: 45,
        parentId: 4,
        name: 'SSH 终端',
        code: 'ssh-manage',
        type: 'menu',
        path: '/system/ssh',
        component: 'system/ssh',
        icon: 'Terminal',
        sort: 5,
        visible: 'visible',
      },
      {
        id: 46,
        parentId: 4,
        name: '备份恢复',
        code: 'backup-manage',
        type: 'menu',
        path: '/system/backup',
        component: 'system/backup',
        icon: 'DataBackup',
        sort: 6,
        visible: 'visible',
      },
      {
        id: 47,
        parentId: 4,
        name: 'MML命令',
        code: 'mml-manage',
        type: 'menu',
        path: '/system/mml',
        component: 'system/mml',
        icon: 'List',
        sort: 7,
        visible: 'visible',
      },
      {
        id: 48,
        parentId: 4,
        name: '安全策略',
        code: 'security-manage',
        type: 'menu',
        path: '/system/security',
        component: 'system/security',
        icon: 'Lock',
        sort: 8,
        visible: 'visible',
      },
      {
        id: 49,
        parentId: 4,
        name: '邮件配置',
        code: 'mail-config',
        type: 'menu',
        path: '/system/mail',
        component: 'system/mail',
        icon: 'Message',
        sort: 9,
        visible: 'visible',
      },
      {
        id: 50,
        parentId: 4,
        name: 'NTP 配置',
        code: 'ntp-config',
        type: 'menu',
        path: '/system/ntp',
        component: 'system/ntp',
        icon: 'Timer',
        sort: 10,
        visible: 'visible',
      },
      {
        id: 51,
        parentId: 4,
        name: '资源监控',
        code: 'resources-monitor',
        type: 'menu',
        path: '/system/resources',
        component: 'system/resources',
        icon: 'Cpu',
        sort: 11,
        visible: 'visible',
      },
      {
        id: 52,
        parentId: 4,
        name: '平台设置',
        code: 'platform-settings',
        type: 'menu',
        path: '/system/platform',
        component: 'system/platform',
        icon: 'Platform',
        sort: 12,
        visible: 'visible',
      },
      {
        id: 53,
        parentId: 4,
        name: '健康检查',
        code: 'health-check',
        type: 'menu',
        path: '/system/health',
        component: 'system/health',
        icon: 'Monitor',
        sort: 13,
        visible: 'visible',
      },
      {
        id: 54,
        parentId: 4,
        name: 'CA 证书',
        code: 'cacert-management',
        type: 'menu',
        path: '/system/cacert',
        component: 'system/cacert',
        icon: 'Key',
        sort: 14,
        visible: 'visible',
      },
      {
        id: 55,
        parentId: 4,
        name: '设备黑名单',
        code: 'black-list',
        type: 'menu',
        path: '/system/blacklist',
        component: 'system/blacklist',
        icon: 'UserFilled',
        sort: 15,
        visible: 'visible',
      },
      {
        id: 56,
        parentId: 4,
        name: '抓包管理',
        code: 'tcpdump',
        type: 'menu',
        path: '/system/tcpdump',
        component: 'system/tcpdump',
        icon: 'Monitor',
        sort: 16,
        visible: 'visible',
      },
      {
        id: 57,
        parentId: 4,
        name: 'PM 文件',
        code: 'pmfile',
        type: 'menu',
        path: '/system/pmfile',
        component: 'system/pmfile',
        icon: 'Document',
        sort: 17,
        visible: 'visible',
      },
      {
        id: 58,
        parentId: 4,
        name: '心跳管理',
        code: 'heartbeat',
        type: 'menu',
        path: '/system/heartbeat',
        component: 'system/heartbeat',
        icon: 'Connection',
        sort: 18,
        visible: 'visible',
      },
      {
        id: 59,
        parentId: 4,
        name: '设备认证',
        code: 'device-auth',
        type: 'menu',
        path: '/system/deviceauth',
        component: 'system/deviceauth',
        icon: 'Lock',
        sort: 19,
        visible: 'visible',
      },
      {
        id: 60,
        parentId: 4,
        name: '北向接口日志',
        code: 'north-interface-log',
        type: 'menu',
        path: '/system/northinterfacelog',
        component: 'system/northinterfacelog',
        icon: 'Message',
        sort: 20,
        visible: 'visible',
      },
    ],
  },
  {
    id: 7,
    parentId: 0,
    name: '统计报表',
    code: 'report',
    type: 'directory',
    path: '/report',
    component: 'Layout',
    icon: 'TrendCharts',
    sort: 6,
    visible: 'visible',
    children: [
      {
        id: 71,
        parentId: 7,
        name: 'MR 报表',
        code: 'mr-report',
        type: 'menu',
        path: '/report/mr',
        component: 'report/mr',
        icon: 'TrendCharts',
        sort: 1,
        visible: 'visible',
      },
      {
        id: 72,
        parentId: 7,
        name: 'PM 性能管理',
        code: 'pm-management',
        type: 'menu',
        path: '/report/pm',
        component: 'report/pm',
        icon: 'DataAnalysis',
        sort: 2,
        visible: 'visible',
      },
    ],
  },
  {
    id: 5,
    parentId: 0,
    name: '个人中心',
    code: 'profile',
    type: 'menu',
    path: '/profile',
    component: 'profile/index',
    icon: 'User',
    sort: 99,
    visible: 'hidden',
  },
];
