/**
 * 前端硬编码菜单配置
 *
 * 对齐原 Java nms-web router/index.js：菜单为前端硬编码，
 * 通过路由 meta.permissionsOr/permissionsAnd/isAdmin 控制可见性。
 *
 * 菜单项与 router/modules/static.ts 中的路由对应。
 *
 * 菜单 name 通过 i18n key 动态转换：
 *   - 若 i18n key 存在，使用 t(key)
 *   - 否则回退到 fallbackName
 */

import type { MenuItem } from '@/types';

export interface MenuConfig {
  id: number;
  parentId: number;
  /** 菜单 i18n key（如 menu.dashboard） */
  i18nKey: string;
  /** 菜单 i18n 缺失时的兜底名称（兼容旧版本） */
  fallbackName: string;
  code: string;
  type: MenuItem['type'];
  path: string;
  component?: string;
  icon?: string;
  permission?: string;
  permissionsOr?: string[];
  permissionsAnd?: string[];
  isAdmin?: boolean;
  sort: number;
  visible: MenuItem['visible'];
  keepAlive?: boolean;
  isExternal?: boolean;
  children?: MenuConfig[];
}

export const staticMenuConfigs: MenuConfig[] = [
  {
    id: 1,
    parentId: 0,
    i18nKey: 'menu.dashboard',
    fallbackName: '仪表盘',
    code: 'dashboard',
    type: 'menu',
    path: '/dashboard',
    component: 'dashboard/index',
    icon: 'Odometer',
    sort: 1,
    visible: 'visible',
    keepAlive: true,
  },
  {
    id: 2,
    parentId: 0,
    i18nKey: 'menu.device',
    fallbackName: '设备管理',
    code: 'device',
    type: 'directory',
    path: '/device',
    component: 'Layout',
    icon: 'Monitor',
    sort: 2,
    visible: 'visible',
    children: [
      {
        id: 21,
        parentId: 2,
        i18nKey: 'menu.deviceList',
        fallbackName: '设备列表',
        code: 'device-list',
        type: 'menu',
        path: '/device/list',
        component: 'device/list',
        icon: 'List',
        sort: 1,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 26,
        parentId: 2,
        i18nKey: 'menu.deviceGroup',
        fallbackName: '设备分组',
        code: 'device-group',
        type: 'menu',
        path: '/device/group',
        component: 'device/group',
        icon: 'Grid',
        sort: 2,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 25,
        parentId: 2,
        i18nKey: 'menu.deviceOps',
        fallbackName: '设备运维',
        code: 'device-ops',
        type: 'menu',
        path: '/device/ops',
        component: 'device/ops',
        icon: 'Operation',
        sort: 5,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 22,
        parentId: 2,
        i18nKey: 'menu.parameterManage',
        fallbackName: '参数管理',
        code: 'parameter-management',
        type: 'menu',
        path: '/device/parameter',
        component: 'device/parameter',
        icon: 'Setting',
        sort: 2,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 23,
        parentId: 2,
        i18nKey: 'menu.paramMonitor',
        fallbackName: '参数监控',
        code: 'param-monitor',
        type: 'menu',
        path: '/device/param-monitor',
        component: 'device/param-monitor',
        icon: 'TrendCharts',
        sort: 3,
        visible: 'visible',
        keepAlive: true,
      },
      {
        id: 24,
        parentId: 2,
        i18nKey: 'menu.paramCompare',
        fallbackName: '参数对比',
        code: 'param-compare',
        type: 'menu',
        path: '/device/param-compare',
        component: 'device/param-compare',
        icon: 'DocumentCopy',
        sort: 4,
        visible: 'visible',
        keepAlive: true,
      },
    ],
  },
  {
    id: 3,
    parentId: 0,
    i18nKey: 'menu.monitor',
    fallbackName: '监控告警',
    code: 'monitor',
    type: 'directory',
    path: '/monitor',
    component: 'Layout',
    icon: 'Bell',
    sort: 3,
    visible: 'visible',
    permissionsOr: ['Alarm.ListAlarm'],
    children: [
      {
        id: 31,
        parentId: 3,
        i18nKey: 'menu.alarmList',
        fallbackName: '告警列表',
        code: 'alarm-list',
        type: 'menu',
        path: '/monitor/alarm',
        component: 'monitor/alarm',
        icon: 'Warning',
        sort: 1,
        visible: 'visible',
        permissionsOr: ['Alarm.ListAlarm'],
      },
      {
        id: 32,
        parentId: 3,
        i18nKey: 'menu.eventLog',
        fallbackName: '事件日志',
        code: 'event-log',
        type: 'menu',
        path: '/monitor/event-log',
        component: 'monitor/event-log',
        icon: 'Document',
        sort: 2,
        visible: 'visible',
      },
      {
        id: 33,
        parentId: 3,
        i18nKey: 'menu.deviceLog',
        fallbackName: '设备日志',
        code: 'device-log',
        type: 'menu',
        path: '/monitor/device-log',
        component: 'monitor/device-log',
        icon: 'Files',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 34,
        parentId: 3,
        i18nKey: 'menu.monitorTask',
        fallbackName: '监控任务',
        code: 'monitor-task',
        type: 'menu',
        path: '/monitor/monitor-task',
        component: 'monitor/monitor-task',
        icon: 'DataLine',
        sort: 4,
        visible: 'visible',
      },
    ],
  },
  {
    id: 6,
    parentId: 0,
    i18nKey: 'menu.network',
    fallbackName: '网络管理',
    code: 'network',
    type: 'directory',
    path: '/network',
    component: 'Layout',
    icon: 'MapLocation',
    sort: 5,
    visible: 'visible',
    children: [
      {
        id: 61,
        parentId: 6,
        i18nKey: 'menu.siteManage',
        fallbackName: '站点管理',
        code: 'site-manage',
        type: 'menu',
        path: '/network/site',
        component: 'network/site',
        icon: 'MapLocation',
        sort: 1,
        visible: 'visible',
      },
      {
        id: 62,
        parentId: 6,
        i18nKey: 'menu.topology',
        fallbackName: '拓扑管理',
        code: 'topology-manage',
        type: 'menu',
        path: '/network/topology',
        component: 'network/topology',
        icon: 'Share',
        sort: 2,
        visible: 'visible',
      },
      {
        id: 63,
        parentId: 6,
        i18nKey: 'menu.cbsd',
        fallbackName: 'CBSD 管理',
        code: 'cbsd-manage',
        type: 'menu',
        path: '/network/cbsd',
        component: 'network/cbsd',
        icon: 'Connection',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 64,
        parentId: 6,
        i18nKey: 'menu.coreNetwork',
        fallbackName: '核心网',
        code: 'core-network',
        type: 'menu',
        path: '/network/core-network',
        component: 'network/core-network',
        icon: 'Monitor',
        sort: 4,
        visible: 'visible',
      },
    ],
  },
  {
    id: 4,
    parentId: 0,
    i18nKey: 'menu.system',
    fallbackName: '系统设置',
    code: 'system',
    type: 'directory',
    path: '/system',
    component: 'Layout',
    icon: 'Setting',
    sort: 4,
    visible: 'visible',
    isAdmin: true,
    children: [
      {
        id: 41,
        parentId: 4,
        i18nKey: 'menu.userManage',
        fallbackName: '用户管理',
        code: 'user-manage',
        type: 'menu',
        path: '/system/user',
        component: 'system/user',
        icon: 'User',
        sort: 1,
        visible: 'visible',
        permissionsOr: ['System.Authority.User.ListUser'],
      },
      {
        id: 42,
        parentId: 4,
        i18nKey: 'menu.roleManage',
        fallbackName: '角色管理',
        code: 'role-manage',
        type: 'menu',
        path: '/system/role',
        component: 'system/role',
        icon: 'UserFilled',
        sort: 2,
        visible: 'visible',
        permissionsOr: ['System.Authority.Role.ListRole'],
      },
      {
        id: 43,
        parentId: 4,
        i18nKey: 'menu.upgrade',
        fallbackName: '升级管理',
        code: 'upgrade-manage',
        type: 'menu',
        path: '/system/upgrade',
        component: 'system/upgrade',
        icon: 'UploadFilled',
        sort: 3,
        visible: 'visible',
      },
      {
        id: 44,
        parentId: 4,
        i18nKey: 'menu.systemSettings',
        fallbackName: '系统配置',
        code: 'system-settings',
        type: 'menu',
        path: '/system/settings',
        component: 'system/settings',
        icon: 'Setting',
        sort: 4,
        visible: 'visible',
      },
      {
        id: 45,
        parentId: 4,
        i18nKey: 'menu.ssh',
        fallbackName: 'SSH 终端',
        code: 'ssh-manage',
        type: 'menu',
        path: '/system/ssh',
        component: 'system/ssh',
        icon: 'Terminal',
        sort: 5,
        visible: 'visible',
      },
      {
        id: 46,
        parentId: 4,
        i18nKey: 'menu.backup',
        fallbackName: '备份恢复',
        code: 'backup-manage',
        type: 'menu',
        path: '/system/backup',
        component: 'system/backup',
        icon: 'DataBackup',
        sort: 6,
        visible: 'visible',
      },
      {
        id: 47,
        parentId: 4,
        i18nKey: 'menu.mml',
        fallbackName: 'MML命令',
        code: 'mml-manage',
        type: 'menu',
        path: '/system/mml',
        component: 'system/mml',
        icon: 'List',
        sort: 7,
        visible: 'visible',
      },
      {
        id: 48,
        parentId: 4,
        i18nKey: 'menu.security',
        fallbackName: '安全策略',
        code: 'security-manage',
        type: 'menu',
        path: '/system/security',
        component: 'system/security',
        icon: 'Lock',
        sort: 8,
        visible: 'visible',
      },
      {
        id: 49,
        parentId: 4,
        i18nKey: 'menu.mailConfig',
        fallbackName: '邮件配置',
        code: 'mail-config',
        type: 'menu',
        path: '/system/mail',
        component: 'system/mail',
        icon: 'Message',
        sort: 9,
        visible: 'visible',
      },
      {
        id: 50,
        parentId: 4,
        i18nKey: 'menu.ntpConfig',
        fallbackName: 'NTP 配置',
        code: 'ntp-config',
        type: 'menu',
        path: '/system/ntp',
        component: 'system/ntp',
        icon: 'Timer',
        sort: 10,
        visible: 'visible',
      },
      {
        id: 51,
        parentId: 4,
        i18nKey: 'menu.resources',
        fallbackName: '资源监控',
        code: 'resources-monitor',
        type: 'menu',
        path: '/system/resources',
        component: 'system/resources',
        icon: 'Cpu',
        sort: 11,
        visible: 'visible',
      },
      {
        id: 52,
        parentId: 4,
        i18nKey: 'menu.platform',
        fallbackName: '平台设置',
        code: 'platform-settings',
        type: 'menu',
        path: '/system/platform',
        component: 'system/platform',
        icon: 'Platform',
        sort: 12,
        visible: 'visible',
      },
      {
        id: 53,
        parentId: 4,
        i18nKey: 'menu.healthCheck',
        fallbackName: '健康检查',
        code: 'health-check',
        type: 'menu',
        path: '/system/health',
        component: 'system/health',
        icon: 'Monitor',
        sort: 13,
        visible: 'visible',
      },
      {
        id: 54,
        parentId: 4,
        i18nKey: 'menu.cacert',
        fallbackName: 'CA 证书',
        code: 'cacert-management',
        type: 'menu',
        path: '/system/cacert',
        component: 'system/cacert',
        icon: 'Key',
        sort: 14,
        visible: 'visible',
      },
      {
        id: 55,
        parentId: 4,
        i18nKey: 'menu.blacklist',
        fallbackName: '设备黑名单',
        code: 'black-list',
        type: 'menu',
        path: '/system/blacklist',
        component: 'system/blacklist',
        icon: 'UserFilled',
        sort: 15,
        visible: 'visible',
      },
      {
        id: 56,
        parentId: 4,
        i18nKey: 'menu.tcpdump',
        fallbackName: '抓包管理',
        code: 'tcpdump',
        type: 'menu',
        path: '/system/tcpdump',
        component: 'system/tcpdump',
        icon: 'Monitor',
        sort: 16,
        visible: 'visible',
      },
      {
        id: 57,
        parentId: 4,
        i18nKey: 'menu.pmfile',
        fallbackName: 'PM 文件',
        code: 'pmfile',
        type: 'menu',
        path: '/system/pmfile',
        component: 'system/pmfile',
        icon: 'Document',
        sort: 17,
        visible: 'visible',
      },
      {
        id: 58,
        parentId: 4,
        i18nKey: 'menu.heartbeat',
        fallbackName: '心跳管理',
        code: 'heartbeat',
        type: 'menu',
        path: '/system/heartbeat',
        component: 'system/heartbeat',
        icon: 'Connection',
        sort: 18,
        visible: 'visible',
      },
      {
        id: 59,
        parentId: 4,
        i18nKey: 'menu.deviceAuth',
        fallbackName: '设备认证',
        code: 'device-auth',
        type: 'menu',
        path: '/system/deviceauth',
        component: 'system/deviceauth',
        icon: 'Lock',
        sort: 19,
        visible: 'visible',
      },
      {
        id: 60,
        parentId: 4,
        i18nKey: 'menu.northInterfaceLog',
        fallbackName: '北向接口日志',
        code: 'north-interface-log',
        type: 'menu',
        path: '/system/northinterfacelog',
        component: 'system/northinterfacelog',
        icon: 'Message',
        sort: 20,
        visible: 'visible',
      },
    ],
  },
  {
    id: 7,
    parentId: 0,
    i18nKey: 'menu.report',
    fallbackName: '统计报表',
    code: 'report',
    type: 'directory',
    path: '/report',
    component: 'Layout',
    icon: 'TrendCharts',
    sort: 6,
    visible: 'visible',
    children: [
      {
        id: 71,
        parentId: 7,
        i18nKey: 'menu.mrReport',
        fallbackName: 'MR 报表',
        code: 'mr-report',
        type: 'menu',
        path: '/report/mr',
        component: 'report/mr',
        icon: 'TrendCharts',
        sort: 1,
        visible: 'visible',
      },
      {
        id: 72,
        parentId: 7,
        i18nKey: 'menu.pm',
        fallbackName: 'PM 性能管理',
        code: 'pm-management',
        type: 'menu',
        path: '/report/pm',
        component: 'report/pm',
        icon: 'DataAnalysis',
        sort: 2,
        visible: 'visible',
      },
    ],
  },
  {
    id: 5,
    parentId: 0,
    i18nKey: 'menu.profile',
    fallbackName: '个人中心',
    code: 'profile',
    type: 'menu',
    path: '/profile',
    component: 'profile/index',
    icon: 'User',
    sort: 99,
    visible: 'hidden',
  },
];

/**
 * 将 MenuConfig 转换为 MenuItem（运行时根据 locale 解析 name）
 */
export function resolveMenuItems(configs: MenuConfig[], t: (key: string) => string): MenuItem[] {
  return configs.map((c) => ({
    id: c.id,
    parentId: c.parentId,
    name: safeT(t, c.i18nKey, c.fallbackName),
    code: c.code,
    type: c.type,
    path: c.path,
    component: c.component,
    icon: c.icon,
    permission: c.permission,
    permissionsOr: c.permissionsOr,
    permissionsAnd: c.permissionsAnd,
    isAdmin: c.isAdmin,
    sort: c.sort,
    visible: c.visible,
    keepAlive: c.keepAlive,
    isExternal: c.isExternal,
    children: c.children ? resolveMenuItems(c.children, t) : undefined,
  }));
}

function safeT(t: (key: string) => string, key: string, fallback: string): string {
  try {
    const v = t(key);
    if (v && v !== key) return v;
  } catch {
    // ignore
  }
  return fallback;
}
